name: .NET PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/dotnet-common.yml
    with:
      publish_output: publish-pr
      create_release: false
    secrets: inherit
